# Generated by Django 4.2.3 on 2023-08-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="ingredient_needed",
            field=models.BooleanField(default=False),
        ),
    ]
