# Generated by Django 4.2.3 on 2023-08-10 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conversion", "0002_measurement_ingredient_needed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="ingredient_needed",
            new_name="volume_unit",
        ),
    ]
