# Generated by Django 4.2.3 on 2023-07-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0003_cookbookuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookbookuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
