# Generated by Django 4.2.3 on 2023-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0004_alter_cookbookuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookbookuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
