# Generated by Django 4.2.3 on 2023-07-28 04:47

import django.core.validators
from django.db import migrations, models
import validators.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user_auth", "0006_alter_cookbookuser_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cookbookuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    validators.validators.validate_image_max_size_1_mb,
                ],
            ),
        ),
    ]
