# Generated by Django 4.2.3 on 2023-08-09 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="note_text",
            field=models.TextField(
                max_length=300,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
    ]
