# Generated by Django 4.2.3 on 2023-08-09 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_note_note_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={"ordering": ["-created_at"]},
        ),
    ]
